### ISSUE TITLE
Can't login as root and blank password on putty

### ISSUE THREAD

**Issue by manobendro** [OLIMEX/ESP32-S3-DevKit-LiPo#1]
I flash olimexS3WROOM_N8qdR8ot.bin rom on yd-esp32-s3-n16-r8 and putty for serial communication with the esp32 board. But I can't log into Linux with username root and password keeping empty. Can anyone tell me the root password or do I need to change the configuration on putty?

**Comment by ESP32DE** [comment]
read commit message to the bin helps
![grafik](https://github.com/user-attachments/assets/35671a4f-39d7-405f-a394-fb596690e3ee)
@manobendro
